Added checkNode.js to enforce version range specified in package.json. Updated preferred node version in .node-version and .nvmrc to match dev environment. Added JSdoc annotation, enabled jsdoc/require-jsdoc warnings. Added jsdoc check to workflow.

diff --git a/.github/workflows/build-and-publish.yml b/.github/workflows/build-and-publish.yml
--- a/.github/workflows/build-and-publish.yml
+++ b/.github/workflows/build-and-publish.yml
@@ -67,6 +67,26 @@ jobs:
       - name: Install Node.js dependencies
         run: npm ci
 
+      - name: Install jq
+        run: sudo apt-get install -y jq
+
+      # Check for proper JSDoc annnotations
+      - name: Run JSDoc lint check
+        run: |
+          set -e
+          output=$(npm run lint:jsdoc || true)
+          echo "$output"
+
+          count=$(echo "$output" | wc -l)
+          if [ "$count" -gt 0 ]; then
+            echo "❌ JSDoc lint check failed with $count violations."
+            exit 1
+          fi
+
+      - name: ✅ Pass
+        if: success()
+        run: echo "JSDoc lint passed successfully!"
+
       # Test to ensure the package is working
       - name: Build Node.js project
         run: npm run build
@@ -105,6 +125,17 @@ jobs:
           git config --global user.email "github@sl.neteng.cc"
           git config --global user.name "SunDevil311"
 
+      - name: Verify version not already published
+        run: |
+          PACKAGE_NAME=$(node -p "require('./package.json').name")
+          PACKAGE_VERSION=$(node -p "require('./package.json').version")
+          echo "Checking if $PACKAGE_NAME@$PACKAGE_VERSION is already published..."
+
+          npm view $PACKAGE_NAME@$PACKAGE_VERSION > /dev/null && {
+            echo "❌ Version $PACKAGE_VERSION already exists on npm. Exiting..."
+            exit 1
+          } || echo "✅ Version is new. Proceeding with publish."
+
       - name: Publish package to npmjs
         run: npm publish --access public
         env:
@@ -136,6 +167,17 @@ jobs:
       - name: Update package name for GPR
         run: |
           sed -i 's/"name": ".*"/"name": "@netwk-pro\/web"/' package.json
+
+      - name: Verify version not already published
+        run: |
+          PACKAGE_NAME=$(node -p "require('./package.json').name")
+          PACKAGE_VERSION=$(node -p "require('./package.json').version")
+          echo "Checking if $PACKAGE_NAME@$PACKAGE_VERSION is already published..."
+
+          npm view $PACKAGE_NAME@$PACKAGE_VERSION > /dev/null && {
+            echo "❌ Version $PACKAGE_VERSION already exists on npm. Exiting..."
+            exit 1
+          } || echo "✅ Version is new. Proceeding with publish."
 
       - name: Publish package to GPR
         run: npm publish
